### ISSUE TITLE
Error running test example

### ISSUE THREAD

**Issue by GattiMh** [JecaTosovic/WaterNetworkAnalysis#16]
Hello

thanks for sharing this tool. I'm trying to run the example shown using `testtopgrams.tpr` and `testtrjgromacs.xtc`.
I've managed to run the notebook but at the last set of instructions I get this error:

```
start the clustering procedure
Nsnaps = 200
WC=WaterClustering(nsnaps= Nsnaps)
perform multi stage reclustering
WC.multi_stage_reclustering(*get_orientations_from_positions(coordO,coordH))
visualise results with pymol
WC.visualise_pymol(aligned_snap, active_site_ids=active_site_resnums, dist=distance)
```

WCW1
 ExecutiveLoad-Detail: Detected chem_comp CIF (.pdbx_model_Cartn_{x,y,z}_ideal)
WCW2
 ExecutiveLoad-Detail: Detected chem_comp CIF (.pdbx_model_Cartn_{x,y,z}_ideal)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 7
      5 WC.multi_stage_reclustering(*get_orientations_from_positions(coordO,coordH))
      6 # visualise results with pymol
----> 7 WC.visualise_pymol(aligned_snap, active_site_ids=active_site_resnums, dist=distance)

File ~/opt/miniconda3/envs/WaterNetworkAnalysis/lib/python3.11/site-packages/ConservedWaterSearch/water_clustering.py:1068, in WaterClustering.visualise_pymol(self, aligned_protein, output_file, active_site_ids, crystal_waters, ligand_resname, dist, density_map)
   1037 def visualise_pymol(
   1038     self,
   1039     aligned_protein: str = "aligned.pdb",
   (...)
   1045     density_map: str | None = None,
   1046 ) -> None:
   1047     """Visualise results using `pymol <[https://pymol.org/>`__](https://pymol.org/%3E%60__).
   1048 
   1049     Args:
   (...)
   1066             visualisation session (usually .dx file). Defaults to None.
   1067     """
-> 1068     visualise_pymol(
   1069         self._water_type,
   1070         self._waterO,
   1071         self._waterH1,
   1072         self._waterH2,
   1073         aligned_protein=aligned_protein,
   1074         output_file=output_file,
   1075         active_site_ids=active_site_ids,
   1076         crystal_waters=crystal_waters,
   1077         ligand_resname=ligand_resname,
   1078         dist=dist,
   1079         density_map=density_map,
   1080     )

File ~/opt/miniconda3/envs/WaterNetworkAnalysis/lib/python3.11/site-packages/ConservedWaterSearch/utils.py:352, in visualise_pymol(water_type, waterO, waterH1, waterH2, aligned_protein, output_file, active_site_ids, crystal_waters, ligand_resname, dist, density_map)
    350     os.remove("hoh.cif")
    351 # save
--> 352 cmd.save(output_file)
    353 cmd.reinitialize()

File ~/opt/miniconda3/envs/WaterNetworkAnalysis/lib/python3.11/site-packages/pymol/exporting.py:834, in save(filename, selection, state, format, ref, ref_state, quiet, partial, _self)
    832 # analyze filename
    833 from pymol.importing import filename_to_format, _eval_func
--> 834 _, _, format_guessed, zipped = filename_to_format(filename)
    835 filename = _self.exp_path(filename)
    837 # file format

File ~/opt/miniconda3/envs/WaterNetworkAnalysis/lib/python3.11/site-packages/pymol/importing.py:42, in filename_to_format(filename)
     41 def filename_to_format(filename):
---> 42     filename = os.path.basename(filename)
     43     pre, delim, ext = filename.rpartition('.')
     45     if ext in ('gz', 'bz2',):

File <frozen posixpath>:142, in basename(p)

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'm working on intel Mac and I have installed the tool using conda in a new env.

Many thanks

**Comment by JecaTosovic** [comment]
Hi, thanks for reporting this.
This is related to a known issue with how macOS interacts with pymol when you use it as a python package (see docs here: https://conservedwatersearch.readthedocs.io/en/latest/Utilities.html#ConservedWaterSearch.utils.visualise_pymol  also pymol docs here: https://pymolwiki.org/index.php/Launching_From_a_Script#Usage). I think I can still make this work with a minor fix to the code. 
For now, I *think* if you just use  `WC.visualise_pymol(aligned_snap, output_file='test.pse', active_site_ids=active_site_resnums, dist=distance)` instead of `WC.visualise_pymol(aligned_snap, active_site_ids=active_site_resnums, dist=distance)` this should work on mac OS as well. I don't have a mac OS machine to test this on. The code will save the visualization state to test.pse file instead of starting an interactive pymol session (since mac OS doesn't support this). But you can open test.pse in pymol as you would open any other file for pymol visualisation and it *should* work.

A separate issue is that if you use the test trajectories (from the repo's tests/data folder) contain only a handful of snapshots (I'm not sure how many exactly), whereas you set `Nsnaps = 200` . The code will run but you will not obtain sensible results. These trajectories were not meant to be used for this purpose but rather for testing some other functions in this repository.

**Comment by JecaTosovic** [comment]
Actually, after some more testing, I realized that this might happen on other OSes if no file name is specified. And I found some more bugs related to this in pymol visualization.

**Comment by DomFijan** [comment]
The problems with visualization are due to errors in the visualization function in [ConservedWaterSearch](https://github.com/JecaTosovic/ConservedWaterSearch).  We have fixed several issues with pymol visualization. To be able to benefit from them you should use the new version of ConservedWaterSearch (0.1.2). The new release of  [CWS](https://pypi.org/project/ConservedWaterSearch/) is already up on PyPi (`pip install conservedwatersearch==0.1.2`). It will probably be up on conda in a couple of hours (`conda install -c conda-forge conservedwatersearch=0.1.2`).
